steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--target",
        "api",
        "-t",
        "gcr.io/$PROJECT_ID/gaffers-exp-api:$COMMIT_SHA",
        "./experiment-backend",
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--target",
        "worker-gpu",
        "-t",
        "gcr.io/$PROJECT_ID/gaffers-exp-worker:$COMMIT_SHA",
        "./experiment-backend",
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/gaffers-exp-api:$COMMIT_SHA"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/gaffers-exp-worker:$COMMIT_SHA"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "gaffers-exp-api",
        "--image",
        "gcr.io/$PROJECT_ID/gaffers-exp-api:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "EXP_MODE=true,EXP_INLINE_WORKER=0",
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "gaffers-exp-worker",
        "--image",
        "gcr.io/$PROJECT_ID/gaffers-exp-worker:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--no-allow-unauthenticated",
        "--set-env-vars",
        "EXP_MODE=true,EXP_TASK_BACKEND=redis,EXP_REDIS_URL=${_EXP_REDIS_URL}",
      ]
