from typing import Any, ContextManager, Protocol

class PipelineObserver(Protocol):
    """
    Observer protocol for recording pipeline execution metrics.
    Decouples the production pipeline from the benchmarking framework.
    """

    def stage(self, stage_id: str, **kwargs: Any) -> ContextManager[Any]:
        """
        Wrap a pipeline stage to observe timing and resource utilization.
        
        Args:
            stage_id: Identifier for the stage (e.g., "stage.calibration").
            **kwargs: Additional contextual data for the stage.
            
        Returns:
            A context manager. The yielded object may optionally have an `extra`
            dictionary attribute to which the pipeline can append dynamic stage data.
        """
        ...
        
    def merge_worker_results(self, worker_results: list[dict[str, Any]]) -> None:
        """
        Merge performance results generated by subprocess workers.
        
        Args:
            worker_results: A list of result dictionaries returned by workers.
        """
        ...
